name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub (if pushing to a private registry)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm64

    - name: create buildx arm builder
      run: docker buildx create --name arm-builder --driver docker-container --platform linux/arm64




  status: 
    name: CI Status
    runs-on: ubuntu-latest
    needs: build
    steps: 
    - run: exit 0