name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    
  merge_group:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub (if pushing to a private registry)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/arm64

    - name: create buildx arm builder
      run: docker buildx create --name arm-builder --driver docker-container --platform linux/arm64


    - name: Build ARM64 image
      uses: docker/build-push-action@v6
      with:
        builder: arm-builder
        platforms: linux/arm64
        file: ./.devcontainer/Dockerfile
        tags: test-image:latest
        push: false
        load: true

    - name: Run tests inside container
      run: |
        docker run --platform linux/arm64 -d -e CONAN_HOME=/workdir/.conan2 --name mycontainer --privileged -v "./:/workspace" test-image:latest /bin/sh -c "sleep infinity"

    - name: run startup script
      run: docker exec mycontainer /bin/sh -c "/workspace/Startup.sh"

    - name: run visitor example
      run: docker exec mycontainer /bin/sh -c "conan create /workspace/visitor"

    - name: stop container
      run: docker stop -t 1  mycontainer 

  status: 
    runs-on: ubuntu-latest
    needs: build
    name: CI Status

    steps:
      - run: exit 0 #to return 1 in case status failure